import { useEffect } from "react";

export default function Index() {
  useEffect(() => {
    const bootstrapUI = async () => {
      var osName: "other" | "windows" = "other";
      if (navigator.appVersion.indexOf("Win") != -1) {
        osName = "windows";
      }

      const fontSize = 80;
      const lineHeight = 1.2;

      const fonts = [
        {
          fileName: "AauxNext-Regular",
          displayName: "AauxNext Regular",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.436,
              ascentDelta: 0.378,
              descentDelta: 0.36,
              capHeight: 0.698,
              xHeight: 0.483,
            },
            other: {
              contentArea: 0.923,
              ascentDelta: 0,
              descentDelta: 0.225,
              capHeight: 0.698,
              xHeight: 0.483,
            },
          },
        },
        {
          fileName: "AauxNext-LightItalic",
          displayName: "AauxNext Light Italic",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.436,
              ascentDelta: 0.378,
              descentDelta: 0.36,
              capHeight: 0.698,
              xHeight: 0.48,
            },
            other: {
              contentArea: 0.923,
              ascentDelta: 0,
              descentDelta: 0.225,
              capHeight: 0.698,
              xHeight: 0.48,
            },
          },
        },
        {
          fileName: "AauxNext-SemiBold",
          displayName: "AauxNext Semi Bold",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.436,
              ascentDelta: 0.378,
              descentDelta: 0.36,
              capHeight: 0.698,
              xHeight: 0.488,
            },
            other: {
              contentArea: 0.923,
              ascentDelta: 0,
              descentDelta: 0.225,
              capHeight: 0.698,
              xHeight: 0.488,
            },
          },
        },
        {
          fileName: "ACaslonPro-Regular",
          displayName: "Adobe Caslon Pro",
          ext: "ttf",
          selection: ["default", "mourning"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.702,
              ascentDelta: 0.267,
              descentDelta: 0.7,
              capHeight: 0.724,
              xHeight: 0.431,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.265,
              capHeight: 0.724,
              xHeight: 0.431,
            },
          },
        },
        {
          fileName: "Albra-Light",
          displayName: "Albra Light",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.371,
              ascentDelta: 0.297,
              descentDelta: 0.288,
              capHeight: 0.715,
              xHeight: 0.478,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.214,
              capHeight: 0.715,
              xHeight: 0.478,
            },
          },
        },
        {
          fileName: "Albra-Medium",
          displayName: "Albra Medium",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.371,
              ascentDelta: 0.297,
              descentDelta: 0.288,
              capHeight: 0.715,
              xHeight: 0.481,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.214,
              capHeight: 0.715,
              xHeight: 0.481,
            },
          },
        },
        {
          fileName: "Albra-Bold",
          displayName: "Albra Bold",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.371,
              ascentDelta: 0.297,
              descentDelta: 0.288,
              capHeight: 0.715,
              xHeight: 0.485,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.214,
              capHeight: 0.715,
              xHeight: 0.485,
            },
          },
        },
        {
          fileName: "AlteHaasGrotesk",
          displayName: "Alte Haas Grotesk",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          lineHeight: 1.2,
          minFontSizeHotFoil: 20,
          metadata: {
            windows: {
              contentArea: 1.165,
              ascentDelta: 0,
              descentDelta: 0.213,
              capHeight: 0.714,
              xHeight: 0.517,
            },
            other: {
              contentArea: 1.165,
              ascentDelta: 0,
              descentDelta: 0.213,
              capHeight: 0.714,
              xHeight: 0.517,
            },
          },
        },
        {
          fileName: "AmerTypewriterITCbyBT-Medium",
          displayName: "American Typewriter",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.181640625,
              ascentDelta: 0.18505859375,
              descentDelta: 0.23681640625,
              capHeight: 0.6748046875,
              xHeight: 0.48583984375,
            },
            other: {
              contentArea: 1.181640625,
              ascentDelta: 0.18505859375,
              descentDelta: 0.23681640625,
              capHeight: 0.6748046875,
              xHeight: 0.48583984375,
            },
          },
        },
        {
          fileName: "AnkeCalligraphicFG",
          displayName: "Anke Calligraphic",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          lineHeight: 1.2,
          minFontSizeHotFoil: 25,
          metadata: {
            windows: {
              contentArea: 1.637,
              ascentDelta: 0,
              descentDelta: 0.589,
              capHeight: 0.742,
              xHeight: 0.5,
            },
            other: {
              contentArea: 1.639,
              ascentDelta: 0.002,
              descentDelta: 0.589,
              capHeight: 0.742,
              xHeight: 0.5,
            },
          },
        },
        {
          fileName: "AnnaClara",
          displayName: "Anna Clara",
          ext: "ttf",
          lineHeight: 1.7,
          selection: ["default", "hotfoil", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          metadata: {
            windows: {
              contentArea: 1.8,
              ascentDelta: 0,
              descentDelta: 0.6,
              capHeight: 0.98,
              xHeight: 0.388,
            },
            other: {
              contentArea: 1.8,
              ascentDelta: 0,
              descentDelta: 0.6,
              capHeight: 0.98,
              xHeight: 0.388,
            },
          },
        },
        {
          fileName: "ArtistampMedium",
          displayName: "Artistamp Medium",
          ext: "ttf",
          selection: ["default", "mourning", "oldRenderer"],
          minFontSize: 9,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.042,
              ascentDelta: 0,
              descentDelta: 0.142,
              capHeight: 0.766,
              xHeight: 0.741,
            },
            other: {
              contentArea: 1.06,
              ascentDelta: 0,
              descentDelta: 0.16,
              capHeight: 0.766,
              xHeight: 0.741,
            },
          },
        },
        {
          fileName: "BellGothicBT-Roman",
          displayName: "Bell Gothic",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.18896484375,
              ascentDelta: 0.193359375,
              descentDelta: 0.23583984375,
              capHeight: 0.6640625,
              xHeight: 0.47802734375,
            },
            other: {
              contentArea: 1.18896484375,
              ascentDelta: 0.193359375,
              descentDelta: 0.23583984375,
              capHeight: 0.6640625,
              xHeight: 0.47802734375,
            },
          },
        },
        {
          fileName: "Belluga-Solid",
          displayName: "Belluga",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 12,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 2.058,
              ascentDelta: 0.359,
              descentDelta: 0.745,
              capHeight: 1.071,
              xHeight: 0.447,
            },
            other: {
              contentArea: 2.058,
              ascentDelta: 0.359,
              descentDelta: 0.745,
              capHeight: 1.071,
              xHeight: 0.447,
            },
          },
        },
        {
          fileName: "BernhardModernBT-Roman",
          displayName: "Bernhard Modern",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          lineHeight: 1.2,
          minFontSizeHotFoil: 20,
          metadata: {
            windows: {
              contentArea: 1.248046875,
              ascentDelta: 0.248046875,
              descentDelta: 0.240234375,
              capHeight: 0.7109375,
              xHeight: 0.35595703125,
            },
            other: {
              contentArea: 1.248046875,
              ascentDelta: 0.248046875,
              descentDelta: 0.240234375,
              capHeight: 0.7109375,
              xHeight: 0.35595703125,
            },
          },
        },
        {
          fileName: "Blossom-Regular",
          displayName: "Blossom",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 18,
          minFontSizeHotFoil: 30,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.124,
              ascentDelta: -0.051,
              descentDelta: 0.309,
              capHeight: 0.727,
              xHeight: 0.369,
            },
            other: {
              contentArea: 1.175,
              ascentDelta: 0,
              descentDelta: 0.309,
              capHeight: 0.727,
              xHeight: 0.369,
            },
          },
        },
        {
          fileName: "BlushAway-Regular",
          displayName: "BlushAway",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 17,
          minFontSizeHotFoil: 30,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.053,
              ascentDelta: -0.051,
              descentDelta: 0.258,
              capHeight: 0.756,
              xHeight: 0.489,
            },
            other: {
              contentArea: 1.105,
              ascentDelta: 0,
              descentDelta: 0.259,
              capHeight: 0.756,
              xHeight: 0.489,
            },
          },
        },
        {
          fileName: "BodoniXT",
          displayName: "Bodoni XT",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          lineHeight: 1.2,
          minFontSizeHotFoil: 25,
          metadata: {
            windows: {
              contentArea: 1.19,
              ascentDelta: -0.001,
              descentDelta: 0.251,
              capHeight: 0.668,
              xHeight: 0.524,
            },
            other: {
              contentArea: 1.14,
              ascentDelta: 0,
              descentDelta: 0.2,
              capHeight: 0.668,
              xHeight: 0.524,
            },
          },
        },
        {
          fileName: "BookmanOldStyle",
          displayName: "Bookman Old Style",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.125,
              ascentDelta: 0.177734375,
              descentDelta: 0.23095703125,
              capHeight: 0.68115234375,
              xHeight: 0.47119140625,
            },
            other: {
              contentArea: 1.173828125,
              ascentDelta: 0.2255859375,
              descentDelta: 0.23193359375,
              capHeight: 0.68115234375,
              xHeight: 0.47119140625,
            },
          },
        },
        {
          fileName: "BudmoJiggler",
          displayName: "Budmo Jiggler",
          ext: "ttf",
          selection: ["default", "mourning", "oldRenderer"],
          minFontSize: 8,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.154,
              ascentDelta: 0.119,
              descentDelta: 0.244,
              capHeight: 0.789,
              xHeight: 0.789,
            },
            other: {
              contentArea: 1.154,
              ascentDelta: 0.119,
              descentDelta: 0.244,
              capHeight: 0.789,
              xHeight: 0.789,
            },
          },
        },
        {
          fileName: "CaliforniaDreamerSans",
          displayName: "California Dreamer Sans",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 12,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.7,
              ascentDelta: 0,
              descentDelta: 0.5,
              capHeight: 0.7,
              xHeight: 0.5,
            },
            other: {
              contentArea: 1.7,
              ascentDelta: 0,
              descentDelta: 0.5,
              capHeight: 0.7,
              xHeight: 0.5,
            },
          },
        },
        {
          fileName: "CaslonOpenfaceBT-Regular",
          displayName: "Caslon Open Face",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 10,
          minFontSizeHotFoil: 40,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.19873046875,
              ascentDelta: 0.203125,
              descentDelta: 0.23583984375,
              capHeight: 0.7060546875,
              xHeight: 0.31494140625,
            },
            other: {
              contentArea: 1.19873046875,
              ascentDelta: 0.203125,
              descentDelta: 0.23583984375,
              capHeight: 0.7060546875,
              xHeight: 0.31494140625,
            },
          },
        },
        {
          fileName: "ChampagneLimousines",
          displayName: "Champagne & Limousines",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 0.99462890625,
              ascentDelta: 0.142578125,
              descentDelta: 0.16162109375,
              capHeight: 0.6904296875,
              xHeight: 0.423828125,
            },
            other: {
              contentArea: 0.99462890625,
              ascentDelta: 0.142578125,
              descentDelta: 0.16162109375,
              capHeight: 0.6904296875,
              xHeight: 0.423828125,
            },
          },
        },
        {
          fileName: "ChopinScript",
          displayName: "Chopin Script",
          ext: "ttf",
          selection: ["default", "mourning", "oldRenderer"],
          minFontSize: 16,
          lineHeight: 1.2,
          minFontSizeHotFoil: 35,
          metadata: {
            windows: {
              contentArea: 1.356,
              ascentDelta: 0,
              descentDelta: 0.426,
              capHeight: 0.788,
              xHeight: 0.329,
            },
            other: {
              contentArea: 1.356,
              ascentDelta: 0,
              descentDelta: 0.426,
              capHeight: 0.788,
              xHeight: 0.329,
            },
          },
        },
        {
          fileName: "CooperBT-Black",
          displayName: "Cooper Black",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          lineHeight: 1.2,
          minFontSizeHotFoil: 25,
          metadata: {
            windows: {
              contentArea: 1.2216796875,
              ascentDelta: 0.203125,
              descentDelta: 0.2587890625,
              capHeight: 0.72802734375,
              xHeight: 0.5400390625,
            },
            other: {
              contentArea: 1.2216796875,
              ascentDelta: 0.203125,
              descentDelta: 0.2587890625,
              capHeight: 0.72802734375,
              xHeight: 0.5400390625,
            },
          },
        },
        {
          fileName: "Cylburn",
          displayName: "Cylburn",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 16,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.211,
              ascentDelta: 0.28,
              descentDelta: 0.394,
              capHeight: 0.598,
              xHeight: 0.279,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.463,
              capHeight: 0.598,
              xHeight: 0.279,
            },
          },
        },
        {
          fileName: "DearRose",
          displayName: "Dear Rose",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 22,
          minFontSizeHotFoil: 35,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.174,
              ascentDelta: -0.05,
              descentDelta: 0.307,
              capHeight: 0.691,
              xHeight: 0.323,
            },
            other: {
              contentArea: 1.224,
              ascentDelta: 0,
              descentDelta: 0.307,
              capHeight: 0.691,
              xHeight: 0.323,
            },
          },
        },
        {
          fileName: "Edwardian Script ITC",
          displayName: "Edwardian Script",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 16,
          lineHeight: 1,
          minFontSizeHotFoil: 30,
          metadata: {
            windows: {
              contentArea: 1.1787109375,
              ascentDelta: 0.001953125,
              descentDelta: 0.328125,
              capHeight: 0.72607421875,
              xHeight: 0.52587890625,
            },
            other: {
              contentArea: 1.1767578125,
              ascentDelta: 0,
              descentDelta: 0.328125,
              capHeight: 0.72607421875,
              xHeight: 0.52587890625,
            },
          },
        },
        {
          fileName: "Elsie-Regular",
          displayName: "Elsie Regular",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.152,
              ascentDelta: 0,
              descentDelta: 0.274,
              capHeight: 0.65,
              xHeight: 0.511,
            },
            other: {
              contentArea: 1.152,
              ascentDelta: 0,
              descentDelta: 0.274,
              capHeight: 0.65,
              xHeight: 0.511,
            },
          },
        },
        {
          fileName: "Elsie-Black",
          displayName: "Elsie Black",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.152,
              ascentDelta: 0,
              descentDelta: 0.274,
              capHeight: 0.7,
              xHeight: 0.543,
            },
            other: {
              contentArea: 1.152,
              ascentDelta: 0,
              descentDelta: 0.274,
              capHeight: 0.7,
              xHeight: 0.543,
            },
          },
        },
        {
          fileName: "FertigoPro-Regular",
          displayName: "Fertigo Pro",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          lineHeight: 1.2,
          minFontSizeHotFoil: 20,
          metadata: {
            windows: {
              contentArea: 1.17,
              ascentDelta: 0.155,
              descentDelta: 0.245,
              capHeight: 0.7,
              xHeight: 0.5,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.23,
              capHeight: 0.7,
              xHeight: 0.5,
            },
          },
        },
        {
          fileName: "Floralies",
          displayName: "Floralies",
          ext: "ttf",
          selection: ["default", "oldRenderer"],
          minFontSize: 10,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.007,
              ascentDelta: 0,
              descentDelta: 0.151,
              capHeight: 0.853,
              xHeight: 0.785,
            },
            other: {
              contentArea: 1.007,
              ascentDelta: 0,
              descentDelta: 0.151,
              capHeight: 0.853,
              xHeight: 0.785,
            },
          },
        },
        {
          fileName: "Linotype-FuturaLTPro-Medium",
          displayName: "Futura LT Pro Medium",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.266,
              ascentDelta: 0.177,
              descentDelta: 0.264,
              capHeight: 0.754,
              xHeight: 0.468,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.175,
              capHeight: 0.754,
              xHeight: 0.468,
            },
          },
        },
        {
          fileName: "AppleGaramond",
          displayName: "Garamond",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 9,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.152,
              ascentDelta: 0.222,
              descentDelta: 0.236,
              capHeight: 0.63,
              xHeight: 0.441,
            },
            other: {
              contentArea: 1.152,
              ascentDelta: 0.222,
              descentDelta: 0.236,
              capHeight: 0.63,
              xHeight: 0.441,
            },
          },
        },
        {
          fileName: "GeosansLight",
          displayName: "Geosans light",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.115,
              ascentDelta: 0,
              descentDelta: 0.212,
              capHeight: 0.714,
              xHeight: 0.413,
            },
            other: {
              contentArea: 1.103,
              ascentDelta: 0,
              descentDelta: 0.2,
              capHeight: 0.714,
              xHeight: 0.413,
            },
          },
        },
        {
          fileName: "GillSansStd",
          displayName: "Gill Sans Standard",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.161,
              ascentDelta: 0.229,
              descentDelta: 0.25,
              capHeight: 0.682,
              xHeight: 0.449,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.318,
              capHeight: 0.682,
              xHeight: 0.449,
            },
          },
        },
        {
          fileName: "Grenouille",
          displayName: "Grenouille",
          ext: "ttf",
          selection: ["default", "mourning", "oldRenderer"],
          minFontSize: 12,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.298,
              ascentDelta: 0.192,
              descentDelta: 0.438,
              capHeight: 0.774,
              xHeight: 0.435,
            },
            other: {
              contentArea: 0.96,
              ascentDelta: 0,
              descentDelta: 0.292,
              capHeight: 0.774,
              xHeight: 0.435,
            },
          },
        },
        {
          fileName: "Helvetica LT",
          displayName: "Helvetica",
          ext: "ttf",
          selection: ["default", "hotfoil", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.5,
          metadata: {
            windows: {
              contentArea: 1.156,
              ascentDelta: 0.213,
              descentDelta: 0.225,
              capHeight: 0.718,
              xHeight: 0.523,
            },
            other: {
              contentArea: 1.156,
              ascentDelta: 0.213,
              descentDelta: 0.225,
              capHeight: 0.718,
              xHeight: 0.523,
            },
          },
        },
        {
          fileName: "Huxtable-Regular",
          displayName: "Huxtable",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 10,
          lineHeight: 1.2,
          minFontSizeHotFoil: 30,
          metadata: {
            windows: {
              contentArea: 1.146,
              ascentDelta: 0.088,
              descentDelta: 0.358,
              capHeight: 0.586,
              xHeight: 0.439,
            },
            other: {
              contentArea: 1.146,
              ascentDelta: 0.088,
              descentDelta: 0.358,
              capHeight: 0.586,
              xHeight: 0.439,
            },
          },
        },
        {
          fileName: "JaneAusten",
          displayName: "Jane Austen",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 12,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.7294921875,
              ascentDelta: 0.4560546875,
              descentDelta: 0.68359375,
              capHeight: 0.8505859375,
              xHeight: 0.32373046875,
            },
            other: {
              contentArea: 1.7294921875,
              ascentDelta: 0.4560546875,
              descentDelta: 0.68359375,
              capHeight: 0.8505859375,
              xHeight: 0.32373046875,
            },
          },
        },
        {
          fileName: "JennaSue",
          displayName: "Jenna Sue",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 14,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.129,
              ascentDelta: -0.01,
              descentDelta: 0.389,
              capHeight: 0.7,
              xHeight: 0.5,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.7,
              xHeight: 0.5,
            },
          },
        },
        {
          fileName: "JosefinSans-Light",
          displayName: "Josefin Sans Light",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.566,
              ascentDelta: 0.492,
              descentDelta: 0.324,
              capHeight: 0.71,
              xHeight: 0.391,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.71,
              xHeight: 0.391,
            },
          },
        },
        {
          fileName: "JosefinSans-LightItalic",
          displayName: "Josefin Sans Light Italic",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.262,
              ascentDelta: 0.241,
              descentDelta: 0.271,
              capHeight: 0.71,
              xHeight: 0.391,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.71,
              xHeight: 0.391,
            },
          },
        },
        {
          fileName: "JosefinSans-Regular",
          displayName: "Josefin Sans Regular",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.566,
              ascentDelta: 0.492,
              descentDelta: 0.324,
              capHeight: 0.723,
              xHeight: 0.414,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.723,
              xHeight: 0.414,
            },
          },
        },
        {
          fileName: "JosefinSans-RegularItalic",
          displayName: "Josefin Sans Regular Italic",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.262,
              ascentDelta: 0.241,
              descentDelta: 0.271,
              capHeight: 0.723,
              xHeight: 0.414,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.723,
              xHeight: 0.414,
            },
          },
        },
        {
          fileName: "JosefinSlab-Regular",
          displayName: "Josefin Slab Regular",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.7,
              xHeight: 0.5,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.7,
              xHeight: 0.5,
            },
          },
        },
        {
          fileName: "JosefinSlab-RegularItalic",
          displayName: "Josefin Slab Regular Italic",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.7,
              xHeight: 0.375,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.7,
              xHeight: 0.375,
            },
          },
        },
        {
          fileName: "JosefinSlab-Bold",
          displayName: "Josefin Slab Bold",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.7,
              xHeight: 0.375,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.7,
              xHeight: 0.375,
            },
          },
        },
        {
          fileName: "JosefinSlab-BoldItalic",
          displayName: "Josefin Slab Bold Italic",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.182,
              ascentDelta: 0.182,
              descentDelta: 0.25,
              capHeight: 0.7,
              xHeight: 0.5,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.7,
              xHeight: 0.5,
            },
          },
        },
        {
          fileName: "KravitzExtraThermal",
          displayName: "Kravitz Extra Thermal",
          ext: "ttf",
          selection: ["default", "hotfoil", "oldRenderer"],
          minFontSize: 8,
          lineHeight: 1.2,
          minFontSizeHotFoil: 30,
          metadata: {
            windows: {
              contentArea: 1.251,
              ascentDelta: 0,
              descentDelta: 0.291,
              capHeight: 0.623,
              xHeight: 0.623,
            },
            other: {
              contentArea: 1.251,
              ascentDelta: 0,
              descentDelta: 0.291,
              capHeight: 0.623,
              xHeight: 0.623,
            },
          },
        },
        {
          fileName: "KudryashevHeadlineSans",
          displayName: "Kudryashev",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.52,
              ascentDelta: 0.27,
              descentDelta: 0.48,
              capHeight: 0.723,
              xHeight: 0.481,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.23,
              capHeight: 0.723,
              xHeight: 0.481,
            },
          },
        },
        {
          fileName: "LiebeErika",
          displayName: "Liebe Erika",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 13,
          minFontSizeHotFoil: 25,
          lineHeight: 1.215,
          metadata: {
            windows: {
              contentArea: 1.075,
              ascentDelta: 0.071,
              descentDelta: 0.264,
              capHeight: 0.682,
              xHeight: 0.468,
            },
            other: {
              contentArea: 1.076,
              ascentDelta: 0.071,
              descentDelta: 0.265,
              capHeight: 0.682,
              xHeight: 0.468,
            },
          },
        },
        {
          fileName: "LiebeGerda-BoldItalic",
          displayName: "Liebe Gerda",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 12,
          lineHeight: 1.2,
          minFontSizeHotFoil: 30,
          metadata: {
            windows: {
              contentArea: 1.90087890625,
              ascentDelta: 0.46435546875,
              descentDelta: 0.77001953125,
              capHeight: 0.634765625,
              xHeight: 0.41650390625,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.33349609375,
              capHeight: 0.634765625,
              xHeight: 0.41650390625,
            },
          },
        },
        {
          fileName: "Lifehack-Regular",
          displayName: "Lifehack",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 10,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.6,
              ascentDelta: 0.37,
              descentDelta: 0.5,
              capHeight: 0.781,
              xHeight: 0.47,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.781,
              xHeight: 0.47,
            },
          },
        },
        {
          fileName: "LittleDays",
          displayName: "Little days",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 11,
          lineHeight: 1.2,
          minFontSizeHotFoil: 25,
          metadata: {
            windows: {
              contentArea: 1.221,
              ascentDelta: 0.067,
              descentDelta: 0.441,
              capHeight: 0.679,
              xHeight: 0.313,
            },
            other: {
              contentArea: 1.122,
              ascentDelta: 0,
              descentDelta: 0.409,
              capHeight: 0.679,
              xHeight: 0.313,
            },
          },
        },
        {
          fileName: "LuxusBrut",
          displayName: "LuxusBrut",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 16,
          minFontSizeHotFoil: 30,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.286,
              ascentDelta: 0.441,
              descentDelta: 0.429,
              capHeight: 0.741,
              xHeight: 0.195,
            },
            other: {
              contentArea: 0.784,
              ascentDelta: 0,
              descentDelta: 0.368,
              capHeight: 0.741,
              xHeight: 0.195,
            },
          },
        },
        {
          fileName: "Luella",
          displayName: "Luella",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 16,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.263,
              ascentDelta: 0,
              descentDelta: 0.288,
              capHeight: 0.761,
              xHeight: 0.55,
            },
            other: {
              contentArea: 1.263,
              ascentDelta: 0,
              descentDelta: 0.288,
              capHeight: 0.761,
              xHeight: 0.55,
            },
          },
        },
        {
          fileName: "Madina-Clean",
          displayName: "Madina",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 16,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.825,
              ascentDelta: 0.015,
              descentDelta: 0.792,
              capHeight: 0.89,
              xHeight: 0.466,
            },
            other: {
              contentArea: 1.825,
              ascentDelta: 0.015,
              descentDelta: 0.792,
              capHeight: 0.89,
              xHeight: 0.466,
            },
          },
        },
        {
          fileName: "MagnoliaSky",
          displayName: "Magnolia Sky",
          ext: "ttf",
          lineHeight: 1.8,
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 10,
          minFontSizeHotFoil: 20,
          metadata: {
            windows: {
              contentArea: 2.146,
              ascentDelta: 0.056,
              descentDelta: 0.758,
              capHeight: 1.006,
              xHeight: 0.585,
            },
            other: {
              contentArea: 2.146,
              ascentDelta: 0.056,
              descentDelta: 0.758,
              capHeight: 1.006,
              xHeight: 0.585,
            },
          },
        },
        {
          fileName: "MardianPro",
          displayName: "Mardian Pro",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 16,
          minFontSizeHotFoil: 35,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.423,
              ascentDelta: 0.171,
              descentDelta: 0.502,
              capHeight: 0.73,
              xHeight: 0.3,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.73,
              xHeight: 0.3,
            },
          },
        },
        {
          fileName: "MinionPro-Regular",
          displayName: "Minion Pro",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.349,
              ascentDelta: 0.262,
              descentDelta: 0.36,
              capHeight: 0.65,
              xHeight: 0.437,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.273,
              capHeight: 0.65,
              xHeight: 0.437,
            },
          },
        },
        {
          fileName: "MrEaves-ModOT-Reg",
          displayName: "Mr Eaves Regular",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.341,
            },
            other: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.341,
            },
          },
        },
        {
          fileName: "MrEaves-ModOT-RegItalic",
          displayName: "Mr Eaves Regular Italic",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.341,
            },
            other: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.341,
            },
          },
        },
        {
          fileName: "MrEaves-ModOT-Bold",
          displayName: "Mr Eaves Bold",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.341,
            },
            other: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.341,
            },
          },
        },
        {
          fileName: "MrsEaves-Petite-Caps-OT",
          displayName: "Mrs Eaves Petite Caps",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 10,
          minFontSizeHotFoil: 30,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.433,
              xHeight: 0.333,
            },
            other: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.433,
              xHeight: 0.333,
            },
          },
        },
        {
          fileName: "MrsEaves-All-Petite-Caps-OT",
          displayName: "Mrs Eaves All Petite Caps",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 10,
          minFontSizeHotFoil: 30,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.333,
              xHeight: 0.333,
            },
            other: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.333,
              xHeight: 0.333,
            },
          },
        },
        {
          fileName: "MrsEaves-OT-Roman",
          displayName: "Mrs Eaves Roman",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 10,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.333,
            },
            other: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.333,
            },
          },
        },
        {
          fileName: "MrsEaves-OT-Bold",
          displayName: "Mrs Eaves Bold",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.333,
            },
            other: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.333,
            },
          },
        },
        {
          fileName: "MrsEaves-OT-Italic",
          displayName: "Mrs Eaves Italic",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.346,
            },
            other: {
              contentArea: 1.11,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.6,
              xHeight: 0.346,
            },
          },
        },
        {
          fileName: "MutluOrnamental",
          displayName: "Mutlu Ornamental",
          ext: "ttf",
          selection: ["default", "oldRenderer"],
          minFontSize: 16,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 2.135,
              ascentDelta: 0,
              descentDelta: 0.652,
              capHeight: 0.79,
              xHeight: 0.814,
            },
            other: {
              contentArea: 2.135,
              ascentDelta: 0,
              descentDelta: 0.652,
              capHeight: 0.79,
              xHeight: 0.814,
            },
          },
        },
        {
          fileName: "NaiveInlineSansBold",
          displayName: "Naive Inline",
          ext: "ttf",
          selection: ["default", "hotfoil", "oldRenderer"],
          minFontSize: 8,
          lineHeight: 1.2,
          minFontSizeHotFoil: 35,
          metadata: {
            windows: {
              contentArea: 1.24,
              ascentDelta: 0.251,
              descentDelta: 0.239,
              capHeight: 0.746,
              xHeight: 0.745,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.746,
              xHeight: 0.745,
            },
          },
        },
        {
          fileName: "Philosopher",
          displayName: "Philosopher",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.04,
              ascentDelta: 0.17,
              descentDelta: 0.21,
              capHeight: 0.66,
              xHeight: 0.47,
            },
            other: {
              contentArea: 1.04,
              ascentDelta: 0.17,
              descentDelta: 0.21,
              capHeight: 0.66,
              xHeight: 0.47,
            },
          },
        },
        {
          fileName: "PinstripeLimo",
          displayName: "Pinstripe Limo",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 10,
          lineHeight: 1.2,
          minFontSizeHotFoil: 40,
          metadata: {
            windows: {
              contentArea: 1.044921875,
              ascentDelta: 0.18994140625,
              descentDelta: 0.20556640625,
              capHeight: 0.6494140625,
              xHeight: 0.421875,
            },
            other: {
              contentArea: 1.044921875,
              ascentDelta: 0.18994140625,
              descentDelta: 0.20556640625,
              capHeight: 0.6494140625,
              xHeight: 0.421875,
            },
          },
        },
        {
          fileName: "TrialbyCupcakes-Quickpen",
          displayName: "Quickpen",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 10,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.875,
              ascentDelta: 0,
              descentDelta: 0.675,
              capHeight: 1.023,
              xHeight: 0.357,
            },
            other: {
              contentArea: 1.875,
              ascentDelta: 0,
              descentDelta: 0.675,
              capHeight: 1.023,
              xHeight: 0.357,
            },
          },
        },
        {
          fileName: "Revista-Regular",
          displayName: "Revista",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.2,
              ascentDelta: 0.2,
              descentDelta: 0.25,
              capHeight: 0.648,
              xHeight: 0.551,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.648,
              xHeight: 0.551,
            },
          },
        },
        {
          fileName: "RobotoCondensed-Light",
          displayName: "Roboto Condensed Light",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.2001953125,
              ascentDelta: 0.2001953125,
              descentDelta: 0.25,
              capHeight: 0.7109375,
              xHeight: 0.5283203125,
            },
            other: {
              contentArea: 1.171875,
              ascentDelta: 0.177734375,
              descentDelta: 0.244140625,
              capHeight: 0.7109375,
              xHeight: 0.5283203125,
            },
          },
        },
        {
          fileName: "RobotoCondensed-Regular",
          displayName: "Roboto Condensed Regular",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.2001953125,
              ascentDelta: 0.2001953125,
              descentDelta: 0.25,
              capHeight: 0.7109375,
              xHeight: 0.5283203125,
            },
            other: {
              contentArea: 1.171875,
              ascentDelta: 0.177734375,
              descentDelta: 0.244140625,
              capHeight: 0.7109375,
              xHeight: 0.5283203125,
            },
          },
        },
        {
          fileName: "RobotoCondensed-RegularItalic",
          displayName: "Roboto Condensed Regular Italic",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 9,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.2001953125,
              ascentDelta: 0.2001953125,
              descentDelta: 0.25,
              capHeight: 0.7109375,
              xHeight: 0.5283203125,
            },
            other: {
              contentArea: 1.171875,
              ascentDelta: 0.177734375,
              descentDelta: 0.244140625,
              capHeight: 0.7109375,
              xHeight: 0.5283203125,
            },
          },
        },
        {
          fileName: "RoseberryBeatriceRegular",
          displayName: "Roseberry Beatrice Regular",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 12,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 2.638,
              ascentDelta: 0.055,
              descentDelta: 1.083,
              capHeight: 1.084,
              xHeight: 0.179,
            },
            other: {
              contentArea: 2.5,
              ascentDelta: 0,
              descentDelta: 1,
              capHeight: 1.084,
              xHeight: 0.179,
            },
          },
        },
        {
          fileName: "Rollerscript-Smooth",
          displayName: "Rollerscript",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 11,
          lineHeight: 1.2,
          minFontSizeHotFoil: 25,
          metadata: {
            windows: {
              contentArea: 1.558,
              ascentDelta: 0.28,
              descentDelta: 0.548,
              capHeight: 0.639,
              xHeight: 0.363,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.27,
              capHeight: 0.639,
              xHeight: 0.363,
            },
          },
        },
        {
          fileName: "Rosalinda-Regular",
          displayName: "Rosalinda",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 10,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 2,
              ascentDelta: 0,
              descentDelta: 0.7,
              capHeight: 1.1,
              xHeight: 0.519,
            },
            other: {
              contentArea: 2,
              ascentDelta: 0,
              descentDelta: 0.7,
              capHeight: 1.1,
              xHeight: 0.519,
            },
          },
        },
        {
          fileName: "Santorini",
          displayName: "Santorini",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 13,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 2.6083984375,
              ascentDelta: 0.86376953125,
              descentDelta: 0.85400390625,
              capHeight: 1.484375,
              xHeight: 0.45751953125,
            },
            other: {
              contentArea: 1.31591796875,
              ascentDelta: 0,
              descentDelta: 0.42529296875,
              capHeight: 1.484375,
              xHeight: 0.45751953125,
            },
          },
        },
        {
          fileName: "Stay Classy Duo Script",
          displayName: "Stay Classy Duo Script",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 15,
          minFontSizeHotFoil: 30,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.723,
              ascentDelta: 0.25,
              descentDelta: 0.801,
              capHeight: 0.835,
              xHeight: 0.265,
            },
            other: {
              contentArea: 1.723,
              ascentDelta: 0.25,
              descentDelta: 0.801,
              capHeight: 0.835,
              xHeight: 0.265,
            },
          },
        },
        {
          fileName: "StyledUp",
          displayName: "Styled Up",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 13,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.066,
              ascentDelta: 0.096,
              descentDelta: 0.28,
              capHeight: 0.77,
              xHeight: 0.42,
            },
            other: {
              contentArea: 1.066,
              ascentDelta: 0.096,
              descentDelta: 0.28,
              capHeight: 0.77,
              xHeight: 0.42,
            },
          },
        },
        {
          fileName: "SunshineCoast",
          displayName: "Sunshine Coast",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 14,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.789,
              ascentDelta: 0.261,
              descentDelta: 0.735,
              capHeight: 0.724,
              xHeight: 0.504,
            },
            other: {
              contentArea: 1.092,
              ascentDelta: 0,
              descentDelta: 0.299,
              capHeight: 0.724,
              xHeight: 0.504,
            },
          },
        },
        {
          fileName: "Tagettes",
          displayName: "Tagettes",
          ext: "ttf",
          lineHeight: 2,
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 9,
          minFontSizeHotFoil: 30,
          metadata: {
            windows: {
              contentArea: 2.07861328125,
              ascentDelta: 0.30224609375,
              descentDelta: 0.751953125,
              capHeight: 1.28759765625,
              xHeight: 0.4248046875,
            },
            other: {
              contentArea: 2.07861328125,
              ascentDelta: 0.30224609375,
              descentDelta: 0.751953125,
              capHeight: 1.28759765625,
              xHeight: 0.4248046875,
            },
          },
        },
        {
          fileName: "ThirstyRoughRegTwo",
          displayName: "Thirsty Rough",
          ext: "ttf",
          selection: ["default", "hotfoil", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.292,
              ascentDelta: 0,
              descentDelta: 0.35,
              capHeight: 0.821,
              xHeight: 0.53,
            },
            other: {
              contentArea: 1.292,
              ascentDelta: 0,
              descentDelta: 0.35,
              capHeight: 0.821,
              xHeight: 0.53,
            },
          },
        },
        {
          fileName: "WalkwayBold",
          displayName: "Walkway Bold",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 8,
          minFontSizeHotFoil: 20,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.053,
              ascentDelta: 0,
              descentDelta: 0.179,
              capHeight: 0.678,
              xHeight: 0.488,
            },
            other: {
              contentArea: 1.053,
              ascentDelta: 0,
              descentDelta: 0.179,
              capHeight: 0.678,
              xHeight: 0.488,
            },
          },
        },
        {
          fileName: "WhiteGarden-Regular",
          displayName: "WhiteGarden Regular",
          ext: "ttf",
          selection: ["default", "mourning", "hotfoil"],
          minFontSize: 16,
          minFontSizeHotFoil: 30,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1.3333333333333333,
              ascentDelta: 0,
              descentDelta: 0.26666666666666666,
              capHeight: 0.9333333333333333,
              xHeight: 0.6666666666666666,
            },
            other: {
              contentArea: 1.3333333333333333,
              ascentDelta: 0,
              descentDelta: 0.26666666666666666,
              capHeight: 0.9333333333333333,
              xHeight: 0.6666666666666666,
            },
          },
        },
        {
          fileName: "WildThings-Sans",
          displayName: "Wild Things",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 11,
          minFontSizeHotFoil: 25,
          lineHeight: 1.2,
          metadata: {
            windows: {
              contentArea: 1,
              ascentDelta: 0.25,
              descentDelta: 0,
              capHeight: 0.694,
              xHeight: 0.696,
            },
            other: {
              contentArea: 1,
              ascentDelta: 0,
              descentDelta: 0.25,
              capHeight: 0.694,
              xHeight: 0.696,
            },
          },
        },
        {
          fileName: "Windsong",
          displayName: "Windsong",
          ext: "ttf",
          selection: ["default", "hotfoil", "mourning", "oldRenderer"],
          minFontSize: 16,
          lineHeight: 1.2,
          minFontSizeHotFoil: 25,
          metadata: {
            windows: {
              contentArea: 1.6746666666666667,
              ascentDelta: 0,
              descentDelta: 0.8786666666666667,
              capHeight: 0.586,
              xHeight: 0.206,
            },
            other: {
              contentArea: 1.6746666666666667,
              ascentDelta: 0,
              descentDelta: 0.8786666666666667,
              capHeight: 0.586,
              xHeight: 0.206,
            },
          },
        },
      ];
      const fontFamily = "MrsEaves-Petite-Caps-OT";
      const fontMetadata = fonts.find(
        (font) => font.fileName === fontFamily
      )?.metadata;
      const font = new FontFace(
        fontFamily,
        `url(https://fonts.stage.celebrate.company/assets/fonts/${fontFamily}.ttf)`
      );
      if (!fontMetadata) {
        throw new Error("no metadata found!");
      }
      // wait for font to be loaded
      await font.load();
      // add font to document
      document.fonts.add(font);
      const lineBoxOverlap = lineHeight - fontMetadata[osName].contentArea;

      document.body.style.setProperty("--fontFamily", fontFamily);
      document.body.style.setProperty("--lineHeight", `${lineHeight}`);
      document.body.style.setProperty("--fontSize", `${fontSize}px`);
      document.body.style.setProperty(
        "--fontAscentDelta",
        `${fontMetadata[osName].ascentDelta + lineBoxOverlap / 2}`
      );
      document.body.style.setProperty(
        "--fontCapHeight",
        `${fontMetadata[osName].capHeight}`
      );
      document.body.style.setProperty(
        "--fontXHeight",
        `${fontMetadata[osName].xHeight}`
      );
      document.body.style.setProperty(
        "--fontDescentDelta",
        `${fontMetadata[osName].descentDelta + lineBoxOverlap / 2}`
      );
    };
    bootstrapUI();
  }, []);
  return (
    <div className="container">
      <div className="wrapper">
        <div className="typo"></div>
        <div className="cap-height"></div>
        <div className="x-height"></div>
        <div className="hhead"></div>
        <div className="text-box">
          <div
            className="text with-fix"
            contentEditable
            role="textbox"
            aria-multiline="true"
            spellCheck="false"
          >
            Mein FoToxbuch 2020
          </div>
        </div>
      </div>
    </div>
  );
}
